# Generated by Django 6.1.1 on 2026-10-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-code', help_text='Font Awesome icon class (e.g., fa-code, fa-database, fa-paint-brush).', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, default='+', max_length=10)),
                ('icon', models.CharField(default='fa-trophy', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='Short tagline shown under your name (used in typing animation).', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated (e.g., Django, PostgreSQL, Tailwind)', max_length=200),
        ),
    ]
